# ==============================================================
# Cấu hình RIÊNG cho inventory-service (Config Server phân phát)
# ==============================================================
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopmart_inventory?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  # Câu 3: Kafka cho inventory-service (trừ kho + compensating hoàn kho)
  kafka:
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.shopmart.inventory.event.OrderEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # Câu 4: Redis + Cache-Aside
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000        # TTL 10 phút cho cache "products"
      cache-null-values: false
